
package espoch.edu.ec.finish.Vista;

import espoch.edu.ec.finish.Controlador.Controlador;
import espoch.edu.ec.finish.Modelo.GestorProductos;
import javax.swing.JRadioButton;

/**
 *
 * @author and_j
 */
public class Vista extends javax.swing.JFrame {
    private Controlador controlador;
    private Listar listar;

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        this.listar= new Listar();
        this.controlador = new Controlador (this, new GestorProductos(), listar);
    }
    // Método para obtener el nombre del producto
    public String getNombre() {
        return txtnombre.getText();
    }

    // Método para obtener el precio del producto
    public double getPrecio() {
        return Double.parseDouble(txtprecio.getText());
    }

    // Método para mostrar mensajes de error
    public void error(String text) {
        labingrese.setText(text);
    }

    // Método para limpiar los campos del formulario
    public void limpiar() {
        txtnombre.setText("");
        txtprecio.setText("");
        btngDisponibleyNo.clearSelection();
    }

    // Método para obtener el estado del producto como String
    public String getEstado() {
        if (btnnselecDisponible.isSelected()) {
            return "true"; // Disponible
        } else if (btnnselecAgotado.isSelected()) {
            return "false"; // Agotado
        } else {
            return "false"; // Por defecto, si no hay selección
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngDisponibleyNo = new javax.swing.ButtonGroup();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        labTitulo = new javax.swing.JLabel();
        labingrese = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnnRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        btnnselecDisponible = new javax.swing.JRadioButton();
        btnnselecAgotado = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labTitulo.setText("Gestión de Productos");

        btnOk.setText("ELIMINAR");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnnRegistro.setText("GUARDAR");
        btnnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnRegistroActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese nombre ");

        jLabel2.setText("Ingrese precio");

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        btngDisponibleyNo.add(btnnselecDisponible);
        btnnselecDisponible.setText("Disponible");
        btnnselecDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnselecDisponibleActionPerformed(evt);
            }
        });

        btngDisponibleyNo.add(btnnselecAgotado);
        btnnselecAgotado.setText("Agotado");
        btnnselecAgotado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnselecAgotadoActionPerformed(evt);
            }
        });

        menu.setText("Menú ");
        menu.setActionCommand("Menú\n");

        jMenuItem1.setText("Listar Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem1);

        jMenuBar1.add(menu);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(labingrese)
                            .addComponent(jLabel1))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtnombre)
                                .addGap(2, 2, 2))
                            .addComponent(txtprecio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(labTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnRegistro)
                    .addComponent(btnnselecDisponible))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnselecAgotado))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labingrese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnnselecDisponible)
                            .addComponent(btnnselecAgotado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnnRegistro)
                            .addComponent(btnOk))
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
     limpiar();       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnnselecDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnselecDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnselecDisponibleActionPerformed

    private void btnnselecAgotadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnselecAgotadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnselecAgotadoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        listar.setVisible(true);
        controlador.listarProductos();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
     
    private void btnnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnRegistroActionPerformed
     this.controlador.agregarProductos();
    }//GEN-LAST:event_btnnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup btngDisponibleyNo;
    private javax.swing.JButton btnnRegistro;
    private javax.swing.JRadioButton btnnselecAgotado;
    private javax.swing.JRadioButton btnnselecDisponible;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel labTitulo;
    private javax.swing.JLabel labingrese;
    private javax.swing.JMenu menu;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
